name: Test and Upload Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        cd toy_calculator
        pytest --cov=calculator --cov-report=xml --cov-report=term
        
    - name: Upload coverage reports to Datadog
      run: datadog-ci coverage upload .
      env:
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_SITE: dd.datad0g.com 
